export  const context  = {
    SET_TOKEN : 'SET_TOKEN',
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_INFO : 'SET_INFO',
    SELECT_PLAYLIST : "SELECT_PLAYLIST",
    SET_PLAYING : 'SET_PLAYING' ,
    SET_STATE_PLAYER : 'SET_STATE_PLAYER'
    ,SET_PLAYLIST_ID:'SET_PLAYLIST_ID'
}